# If this proxy listens on a virtual host with a different hostname, 
# set the environment property OIDC_URL with the virtual host hostname

runtime: node
runtimeVersion: 12.8.1
application: request-test
env:
  - name: NODE_ENV
    value: production
  - name: LOG_LEVEL
    value: 5
  - name: DEBUG
    value: oidc-provider:*

