swagger: "2.0"
info:
  description: API sets created by the Australian Consumer Data Standards to meet the needs
    of the Consumer Data Right
  version: 1.2.0
  title: Consumer Data Standards
  contact:
    name: APIBank CDS Team
    url: https://apibank.com.au/cds
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
host: openbank-aunz-test.apigee.net
basePath: /cds-au/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /discovery/status:
    get:
      tags:
        - Common
        - Discovery
      summary: Get Status
      description: Obtain a health check status for the implementation
      operationId: getStatus
      parameters:
        - name: x-v
          in: header
          description: Version of the API end point requested by the client. Must be set to
            a positive integer. The data holder should respond with the highest
            supported version between [x-min-v](#request-headers) and
            [x-v](#request-headers). If the value of [x-min-v](#request-headers)
            is equal to or higher than the value of [x-v](#request-headers) then
            the [x-min-v](#request-headers) header should be treated as absent.
            If all versions requested are not supported then the data holder
            should respond with a 406 Not Acceptable. See [HTTP
            Headers](#request-headers)
          required: true
          type: string
        - name: x-min-v
          in: header
          description: Minimum version of the API end point requested by the client. Must
            be set to a positive integer if provided. The data holder should
            respond with the highest supported version between
            [x-min-v](#request-headers) and [x-v](#request-headers). If all
            versions requested are not supported then the data holder should
            respond with a 406 Not Acceptable.
          required: false
          type: string
      responses:
        "200":
          description: Success
          headers:
            x-v:
              type: string
              description: The [version](#response-headers) of the API end point that the
                data holder has responded with.
          schema:
            $ref: "#/definitions/ResponseCommonDiscoveryStatus"
      x-version: "1"
  /discovery/outages:
    get:
      tags:
        - Common
        - Discovery
      summary: Get Outages
      description: Obtain a list of scheduled outages for the implementation
      operationId: getOutages
      parameters:
        - name: x-v
          in: header
          description: Version of the API end point requested by the client. Must be set to
            a positive integer. The data holder should respond with the highest
            supported version between [x-min-v](#request-headers) and
            [x-v](#request-headers). If the value of [x-min-v](#request-headers)
            is equal to or higher than the value of [x-v](#request-headers) then
            the [x-min-v](#request-headers) header should be treated as absent.
            If all versions requested are not supported then the data holder
            should respond with a 406 Not Acceptable. See [HTTP
            Headers](#request-headers)
          required: true
          type: string
        - name: x-min-v
          in: header
          description: Minimum version of the API end point requested by the client. Must
            be set to a positive integer if provided. The data holder should
            respond with the highest supported version between
            [x-min-v](#request-headers) and [x-v](#request-headers). If all
            versions requested are not supported then the data holder should
            respond with a 406 Not Acceptable.
          required: false
          type: string
      responses:
        "200":
          description: Success
          headers:
            x-v:
              type: string
              description: The [version](#response-headers) of the API end point that the
                data holder has responded with.
          schema:
            $ref: "#/definitions/ResponseDiscoveryOutagesList"
      x-version: "1"
definitions:
  ResponseCommonDiscoveryStatus:
    type: object
    required:
      - data
      - links
    properties:
      data:
        $ref: "#/definitions/ResponseCommonDiscoveryStatus_data"
      links:
        $ref: "#/definitions/Links"
      meta:
        $ref: "#/definitions/Meta"
  ResponseDiscoveryOutagesList:
    type: object
    required:
      - data
      - links
    properties:
      data:
        $ref: "#/definitions/ResponseDiscoveryOutagesList_data"
      links:
        $ref: "#/definitions/Links"
      meta:
        $ref: "#/definitions/Meta"
  DiscoveryOutage:
    type: object
    required:
      - duration
      - explanation
      - outageTime
    properties:
      outageTime:
        type: string
        description: Date and time that the outage is scheduled to begin
        x-cds-type: DateTimeString
      duration:
        type: string
        description: Planned duration of the outage. Formatted according to [ISO 8601
          Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes
          recurrence syntax)
        x-cds-type: ExternalRef
      isPartial:
        type: boolean
        description: Flag that indicates, if present and set to true, that the outage is
          only partial meaning that only a subset of normally available end
          points will be affected by the outage
      explanation:
        type: string
        description: Provides an explanation of the current outage that can be displayed to
          an end customer
  Links:
    type: object
    required:
      - self
    properties:
      self:
        type: string
        description: Fully qualified link that generated the current response document
        x-cds-type: URIString
  Meta:
    type: object
  ResponseCommonDiscoveryStatus_data:
    required:
      - status
      - updateTime
    properties:
      status:
        type: string
        description: Enumeration with values. OK (implementation is fully functional).
          PARTIAL_FAILURE (one or more end points are unexpectedly unavailable).
          UNAVAILABLE (the full implementation is unexpectedly unavailable).
          SCHEDULED_OUTAGE (an advertised outage is in effect)
        enum:
          - OK
          - PARTIAL_FAILURE
          - UNAVAILABLE
          - SCHEDULED_OUTAGE
      explanation:
        type: string
        description: Provides an explanation of the current outage that can be displayed to
          an end customer. Mandatory if the status property is any value other
          than OK
      detectionTime:
        type: string
        description: The date and time that the current outage was detected. Should only be
          present if the status property is PARTIAL_FAILURE or UNAVAILABLE
        x-cds-type: DateTimeString
      expectedResolutionTime:
        type: string
        description: The date and time that full service is expected to resume (if known).
          Should not be present if the status property has a value of OK.
        x-cds-type: DateTimeString
      updateTime:
        type: string
        description: The date and time that this status was last updated by the Data Holder.
        x-cds-type: DateTimeString
  ResponseDiscoveryOutagesList_data:
    required:
      - outages
    properties:
      outages:
        type: array
        description: List of scheduled outages. Property is mandatory but may contain and
          empty list if no outages are scheduled
        items:
          $ref: "#/definitions/DiscoveryOutage"
parameters:
  RequestHeader_x-v:
    name: x-v
    in: header
    description: Version of the API end point requested by the client. Must be set to a
      positive integer. The data holder should respond with the highest
      supported version between [x-min-v](#request-headers) and
      [x-v](#request-headers). If the value of [x-min-v](#request-headers) is
      equal to or higher than the value of [x-v](#request-headers) then the
      [x-min-v](#request-headers) header should be treated as absent. If all
      versions requested are not supported then the data holder should respond
      with a 406 Not Acceptable. See [HTTP Headers](#request-headers)
    required: true
    type: string
  RequestHeader_x-min-v:
    name: x-min-v
    in: header
    description: Minimum version of the API end point requested by the client. Must be set
      to a positive integer if provided. The data holder should respond with the
      highest supported version between [x-min-v](#request-headers) and
      [x-v](#request-headers). If all versions requested are not supported then
      the data holder should respond with a 406 Not Acceptable.
    required: false
    type: string
  RequestHeader_x-fapi-interaction-id:
    name: x-fapi-interaction-id
    in: header
    description: An [RFC4122](https://tools.ietf.org/html/rfc4122) UUID used as a
      correlation id. If provided, the data holder must play back this value in
      the x-fapi-interaction-id response header. If not provided a [RFC4122]
      UUID value is required to be provided in the response header to track the
      interaction.
    required: false
    type: string
  RequestHeader_x-fapi-auth-date:
    name: x-fapi-auth-date
    in: header
    description: The time when the customer last logged in to the data recipient. Required
      for all resource calls (customer present and unattended). Not to be
      included for unauthenticated calls.
    required: false
    type: string
  RequestHeader_x-fapi-customer-ip-address:
    name: x-fapi-customer-ip-address
    in: header
    description: The customer's original IP address if the customer is currently logged in
      to the data recipient. The presence of this header indicates that the API
      is being called in a customer present context. Not to be included for
      unauthenticated calls.
    required: false
    type: string
  RequestHeader_x-cds-client-headers:
    name: x-cds-client-headers
    in: header
    description: The customer's original standard http headers
      [Base64](#common-field-types) encoded, including the original User Agent
      header, if the customer is currently logged in to the data recipient.
      Mandatory for customer present calls.  Not required for unattended or
      unauthenticated calls.
    required: false
    type: string
    x-cds-type: Base64
  ParamAccountOpenStatus:
    name: open-status
    in: query
    description: Used to filter results according to open/closed status. Values can be
      OPEN, CLOSED or ALL. If absent then ALL is assumed
    required: false
    type: string
    default: ALL
    enum:
      - OPEN
      - CLOSED
      - ALL
  ParamProductCategory:
    name: product-category
    in: query
    description: Used to filter results on the productCategory field applicable to
      accounts. Any one of the valid values for this field can be supplied. If
      absent then all accounts returned.
    required: false
    type: string
    enum:
      - TRANS_AND_SAVINGS_ACCOUNTS
      - TERM_DEPOSITS
      - TRAVEL_CARDS
      - REGULATED_TRUST_ACCOUNTS
      - RESIDENTIAL_MORTGAGES
      - CRED_AND_CHRG_CARDS
      - PERS_LOANS
      - MARGIN_LOANS
      - LEASES
      - TRADE_FINANCE
      - OVERDRAFTS
      - BUSINESS_LOANS
  ParamAccountIsOwned:
    name: is-owned
    in: query
    description: Filters accounts based on whether they are owned by the authorised
      customer.  True for owned accounts, false for unowned accounts and absent
      for all accounts
    required: false
    type: boolean
    x-cds-type: Boolean
  ParamPage:
    name: page
    in: query
    description: Page of results to request (standard pagination)
    required: false
    type: integer
    default: 1
    x-cds-type: PositiveInteger
  ParamPageSize:
    name: page-size
    in: query
    description: Page size to request. Default is 25 (standard pagination)
    required: false
    type: integer
    default: 25
    x-cds-type: PositiveInteger
  ParamTransactionNewestTime:
    name: newest-time
    in: query
    description: Constrain the transaction history request to transactions with effective
      time at or before this date/time.  If absent defaults to today.  Format is
      aligned to DateTimeString common type
    required: false
    type: string
    x-cds-type: DateTimeString
  ParamTransactionOldestTime:
    name: oldest-time
    in: query
    description: Constrain the transaction history request to transactions with effective
      time at or after this date/time. If absent defaults to newest-time minus
      90 days.  Format is aligned to DateTimeString common type
    required: false
    type: string
    x-cds-type: DateTimeString
  ParamTransactionMinAmount:
    name: min-amount
    in: query
    description: Filter transactions to only transactions with amounts higher or equal to
      than this amount
    required: false
    type: string
    x-cds-type: AmountString
  ParamTransactionMaxAmount:
    name: max-amount
    in: query
    description: Filter transactions to only transactions with amounts less than or equal
      to than this amount
    required: false
    type: string
    x-cds-type: AmountString
  ParamTransactionText:
    name: text
    in: query
    description: Filter transactions to only transactions where this string value is found
      as a substring of either the reference or description fields. Format is
      arbitrary ASCII string. This parameter is optionally implemented by data
      holders. If it is not implemented then a response should be provided as
      normal without text filtering applied and an additional boolean field
      named isQueryParamUnsupported should be included in the meta object and
      set to true (whether the text parameter is supplied or not)
    required: false
    type: string
